server:
  port: 8099

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**/*.xml